-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('FRIEND_REQUEST', 'FRIEND_ACCEPTED', 'REJECTED', 'GROUP_INVITE', 'GROUP_JOINED', 'GROUP_LEFT', 'NEW_POST', 'NEW_COMMENT', 'GOAL_CREATED', 'GOAL_COMPLETED', 'PROPOSAL_CREATED', 'PROPOSAL_WINNER', 'NEW_VOTE', 'CHALLENGE_STARTED', 'CHALLENGE_COMPLETED', 'CHALLENGE_ARCHIVED', 'PROGRESS_UPDATE') NOT NULL;
